'use client'

import { Layout } from '@/components/Layout'

export default function PrivacyPolicy() {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        
        <div className="prose max-w-none">
          <p className="mb-4">Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Introduction</h2>
          <p className="mb-4">
            Massage Chair Review ("we", "our", or "this website") respects your privacy and is committed to protecting your personal data. This privacy policy will inform you about how we handle your personal data, including data collected when you visit our website, and about your privacy rights and legal protections.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Information We Collect</h2>
          <p className="mb-4">We may collect, use, store, and transfer different kinds of personal data about you, including:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Identity Data: name, username, or similar identifier</li>
            <li>Contact Data: email address and telephone number</li>
            <li>Technical Data: internet protocol (IP) address, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform</li>
            <li>Usage Data: information about how you use our website and services</li>
          </ul>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">How We Use Your Information</h2>
          <p className="mb-4">We use your personal data for the following purposes:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>To provide and maintain our service</li>
            <li>To notify you about changes to our service</li>
            <li>To allow you to participate in interactive features of our service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our service</li>
            <li>To monitor the usage of our service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Cookies and Tracking Technologies</h2>
          <p className="mb-4">
            We use cookies and similar tracking technologies to track activity on our website and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier.
          </p>
          <p className="mb-4">
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our service.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Google AdSense & Advertising</h2>
          <p className="mb-4">
            This website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). Google AdSense uses "cookies," which are text files placed on your computer, to help the website analyze how users use the site. Google AdSense also uses web beacons (invisible graphics). Through these web beacons, information such as visitor traffic on these pages can be evaluated.
          </p>
          <p className="mb-4">
            The information generated by cookies and web beacons about the use of this website (including your IP address) and delivery of advertising formats are transmitted to and stored by Google on servers in the United States. This information can be passed on by Google to contractual partners of Google. However, Google will not merge your IP address with other data stored by you.
          </p>
          <p className="mb-4">
            You can prevent the installation of cookies by setting your browser software accordingly; however, please note that if you do this, you may not be able to use the full functionality of this website. By using this website, you declare that you agree to the processing of data collected about you by Google in the manner described and for the purpose set out above.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Affiliate Disclosure</h2>
          <p className="mb-4">
            This website contains affiliate links, which means we may receive a commission if you click on a link and purchase something that we have recommended. While clicking these links won't cost you any extra money, they will help us keep this site up and running. Please note that we only recommend products that we believe will be of value to our readers.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to This Privacy Policy</h2>
          <p className="mb-4">
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "last updated" date at the top of this Privacy Policy.
          </p>
          <p className="mb-4">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
          <p className="mb-4">
            If you have any questions about this Privacy Policy, please contact us at:
          </p>
          <p className="mb-4">
            Email: info@massagechairreview.shop
          </p>
        </div>
      </div>
    </Layout>
  )
}